version: '2.3'
services:
  jupyter:
    container_name: 'docker_ai_ssh'
    image: img_docker_ai_ssh
    volumes:
        - ../../../git/:/learning/
    ports:
        - 8888:8888 # exposed port for jupyter
        - "9876:22"
    #runtime: nvidia
    working_dir: /learning/
    #restart: always # start with system
    environment:
        - NVIDIA_VISIBLE_DEVICES=0 # which gpu do you want to use for this container
