version: '2.3'
services:
  jupyter:
    container_name: 'docker_thi_test_gpu'
    image: img_quick_test_gpu
    volumes:
        - .:/srv/ # notebook directory
    ports:
        - 8888:8888 # exposed port for jupyter
    runtime: nvidia
    working_dir: /thi
