version: '2.3'
services:
  jupyter:
    container_name: 'container_ai'
    image: img_ai
    volumes:
        - ../../../git/:/git/
    ports:
        - 8888:8888 # exposed port for jupyter
        - "6789:22"
    runtime: nvidia
    working_dir: /git/
    #restart: always # start with system
    # environment:
    #     - NVIDIA_VISIBLE_DEVICES=0 # which gpu do you want to use for this container
